---
title: "Introduction to kpodcluster"
output: html_notebook
---

One of the most common clustering algorithms used by data scientists today is k-means clustering.  
When attempting to perform k-means clustering on data sets with missing entries, one faces the following options before proceeding to the clustering:

***
1. eliminate the observations with missing features from the data set, then perform k-means clustering on partial data;

2. impute the missing values using certain algorithm, then perform k-means clustering on imputed data;

3. contact the data collecting agency for clarification on the missing values.

***

However, all these options are either computationally expensive, or insufficient in producing the ideal clustering results. The kpodcluster package's k-POD method offers an efficient alternative to resolve the difficulties of applying k-means clustering on incomplete data. *need to sell kpod more here, refer to the paper*

## Example Data
```{r exampleData}
library(kpodclustr)
kpodclustr::makeData(p = 2, n = 10, k = 3, sigma = 0.25, missing = 0.2, seed = 1991)
```

*explain data sets that are generated, complete and incomplete.*

## Usage of k-POD

*explain the returned items when passing the generated incomplete data through kpod()*

## Sufficiency comparison: k-means vs k-pod

*Scatter plots, and rand index*


